### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by SethKitchen** [Nasdin/ReinforcementLearning-AtariGame#2]
How do I test this?

**Comment by Nasdin** [comment]
On the bottom of the jupyter notebook, you can run games by running the cells at the bottom.
You can also change the games which are being run by changing e.g pacman into spaceinvaders.
The types of games that can be run are provided in the output cell from the env list.
There is also a cell for training the models, it loads whatever model already trained and then builds on top of it.

**Comment by SethKitchen** [comment]
I think it would be great if I could use this with my own game. Any way to implement it so that it can use any key from the keyboard as input and use an exe or browser game?

**Comment by alanneoh** [comment]
Yeah I think I might have time to make this modular
